# A sample Gemfile
source "https://rubygems.org"

  gem 'sass',          '~> 3.4.13'
  gem 'compass',       '~> 1.0.3'
  gem 'json',          '~> 1.8.2'
  gem 'breakpoint',    '~> 2.5.0'
  gem 'susy',          '~> 2.2.2'
